### ISSUE TITLE
How to run over your default class with my custom class???

### ISSUE THREAD

**Issue by AleksandarMiha** [BrightspaceUI/dropdown#166]
Hi I need only to change one your class? I can't use this blue link border and background... Only one think how to change this class class="d2l-menu-items d2l-hierarchical-view-content" .... How to target this class in my custom css?

**Comment by AleksandarMiha** [comment]
I try  to target .d2l-menu-items d2l-hierarchical-view-content { 
// unset here but not work
}

**Comment by AleksandarMiha** [comment]
All think what I need to change this https://ibb.co/9NN66mr and on next page, same thing.... I am sure there is a way to change this and you know the way to do it in my CSS

**Comment by dlockhart** [comment]
These styles are actually defined [in the menu component](https://github.com/BrightspaceUI/menu/blob/master/d2l-menu.js#L50). There's no way to style those components from the outside -- that's how encapsulation works with custom elements. The only way you could do it would be to set those `--d2l-color-gypsum` custom properties to something else from outside the element.

For example:
```css
html {
    --d2l-color-gypsum: red;
}
```

But that's going to change everything using gypsum to red, which may not be what you want.

**Comment by AleksandarMiha** [comment]
Nice! But how to unset background and border-top ?

**Comment by dlockhart** [comment]
If the properties you want to unset aren't using a custom property, then there's no way to change them. I'd suggest forking the repo and then you can make whatever changes you want.

**Comment by AleksandarMiha** [comment]
How i can do without forking ? 
Maybe to set all blue color to white? 
Can I set different font-size for text after selected?

**Comment by AleksandarMiha** [comment]
I finished all dropdown. Worked on it 2 days...I can't now change plugin because one blue link..

**Comment by AleksandarMiha** [comment]
How to change font ?!

**Comment by AleksandarMiha** [comment]
Font-size set on 22px and that is all. Thank you!

**Comment by AleksandarMiha** [comment]
@dlockhart Can please send me how to run over font-size for selected first item ? That item get small font size. I don't know how to fork repo and change...

**Comment by AleksandarMiha** [comment]
Also one very important think.. Why this plugin not work on mozilla and safari?
