### ISSUE TITLE
Dropdown menu not supported for Mozilla Firefox, Edge and Safari

### ISSUE THREAD

**Issue by AleksandarMiha** [BrightspaceUI/dropdown#168]
Hi your plugin not supported for Mozilla Firefox, Edge and Safari ? How I can fix it?
I use this version like a cdn:
    <link rel="import" href="https://raw-dot-custom-elements.appspot.com/BrightspaceUI/dropdown/v6.6.1/dropdown/d2l-dropdown.html">
    <link rel="import" href="https://raw-dot-custom-elements.appspot.com/BrightspaceUI/dropdown/v6.6.1/dropdown/d2l-menu/d2l-menu.html">
    <link rel="import" href="https://raw-dot-custom-elements.appspot.com/BrightspaceUI/dropdown/v6.6.1/dropdown/d2l-dropdown-menu.html">
 
and not work for this browser..How to fix this? 
@dbatiste
@dlockhart
@edwardg8
@awikkerink

**Comment by dlockhart** [comment]
This is built using Google Polymer 3 and web components, which are supported in Chrome and newer versions of Safari and Firefox. Edge does not support web components, so you need to include a polyfill for it -- [Polymer browser support information is here](https://polymer-library.polymer-project.org/3.0/docs/browsers) and [polyfill information is here](https://polymer-library.polymer-project.org/3.0/docs/polyfills).

**Comment by AleksandarMiha** [comment]
I use this version
    <link rel="import"
        href="https://raw-dot-custom-elements.appspot.com/BrightspaceUI/dropdown/v6.6.1/dropdown/d2l-dropdown.html">
    <link rel="import"
        href="https://raw-dot-custom-elements.appspot.com/BrightspaceUI/dropdown/v6.6.1/dropdown/d2l-dropdown-content.html">
    <link rel="import"
        href="https://raw-dot-custom-elements.appspot.com/BrightspaceUI/dropdown/v6.6.1/dropdown/d2l-menu/d2l-menu.html">
    <link rel="import"
        href="https://raw-dot-custom-elements.appspot.com/BrightspaceUI/dropdown/v6.6.1/dropdown/d2l-dropdown-menu.html">

And not supported on safari and firefox..Not work

**Comment by awikkerink** [comment]
The latest version is 7.4.1. The file to use has been changed to d2l-dropdown.js.

The links @dlockhart suggested give instructions on how to use it. The demo files give example usages. You'll need the polymer-cli to build the app for browsers that don't support the web components spec or es6

**Comment by AleksandarMiha** [comment]
Can I use polymer like a cdn ?

**Comment by awikkerink** [comment]
You can, but you need to build a Polymer 3 app then upload those files to a CDN.

We don't have a separate CDN for individual components, but only for individual apps.

**Comment by AleksandarMiha** [comment]
Did you have any guide how to use Polymer 3?

**Comment by awikkerink** [comment]
https://www.webcomponents.org/introduction

**Comment by dlockhart** [comment]
Since you're pulling version 6, that's built with Polymer 1 -- [their documentation is here](https://polymer-library.polymer-project.org/1.0/docs/devguide/feature-overview). If you use version 7 like @awikkerink mentioned, that's built with [Polymer 3](https://polymer-library.polymer-project.org/3.0/docs/devguide/feature-overview).

I'm guessing you just aren't including the web component polyfill in your `<head>` before you load any of the imports: `https://cdnjs.cloudflare.com/ajax/libs/webcomponentsjs/1.3.3/webcomponents-loader.js`

**Comment by awikkerink** [comment]
https://www.webcomponents.org/polyfills

**Comment by AleksandarMiha** [comment]
@dlockhart  only import 
 <link href="https://cdnjs.cloudflare.com/ajax/libs/webcomponentsjs/1.3.3/webcomponents-loader.js">
before all link in head and it will work?

**Comment by dlockhart** [comment]
I don't know for certain, but that's a guess. If you could put a demo up of the code breaking on somewhere like jsbin or codepen then we could give more specific help.

**Comment by AleksandarMiha** [comment]
https://codepen.io/mihaufs/pen/PMvNvJ?editors=1010 
Example.

**Comment by dlockhart** [comment]
The polyfill needs to be loaded as a script, not an import. So it should be:

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/webcomponentsjs/1.3.3/webcomponents-loader.js"></script>
```

**Comment by AleksandarMiha** [comment]
Nice nice. Vote up!

**Comment by AleksandarMiha** [comment]
https://ibb.co/HXPM2Gj 
Only one think more. 
Why this is on chrome good, but on mozilla and edge like a top:0 px ?

**Comment by dlockhart** [comment]
Not sure -- again, a codepen that demonstrates the problem would help a lot.

**Comment by AleksandarMiha** [comment]
I am remove pointer. set  top: unset and dropdown content is good top: 0 on chrome. I will provide codepen

**Comment by AleksandarMiha** [comment]
https://codepen.io/mihaufs/pen/PMvNvJ

**Comment by dlockhart** [comment]
What are you trying to do by unsetting the `top`? Shadow DOM doesn't allow you to reach into it like that and change the style of things.

The way dropdown works is that it'll try to automatically position itself either above or below the opener. By unsetting `top` like that you're going to mess it up. It has [options to adjust the vertical offset and alignment](https://github.com/BrightspaceUI/dropdown#dropdown-contents) if that's what you're trying to do.

**Comment by AleksandarMiha** [comment]
Only set vertical-offset? 
<d2l-dropdown-menu id="dropdown"  min-width="300" min-width="300" no-pointer vertical-offset>
??
not work

**Comment by awikkerink** [comment]
vertical-offset requires a value. What are you trying to do by unsetting `top` or setting `vertical-offset`?

**Comment by dlockhart** [comment]
Vertical offset goes on `<d2l-dropdown-menu>`:

```html
<d2l-dropdown-menu id="dropdown" min-width="340" no-pointer vertical-offset="100">
```

Positive values move it down, negative values move it up.

**Comment by AleksandarMiha** [comment]
Top

**Comment by AleksandarMiha** [comment]
vertical-offset="0" 
Finallyy my dropdown is finished!!!!!
Thank you so much for all!
