### ISSUE TITLE
How to change arrow in menu?

### ISSUE THREAD

**Issue by AleksandarMiha** [BrightspaceUI/dropdown#172]
I need change color of dropdown menu arrow. How that it? Help
Which class or id I need to use? 
Or where is set that? i have js file in my project d2l-menu-item-styles.js 
What i need do to change color of arrow.
Also one important think,
how to remove border-radius on drop down menu corners?
Help

**Comment by AleksandarMiha** [comment]
@dlockhart 
@BoGs 
@omsmith 
@xraysaas

**Comment by AleksandarMiha** [comment]
@dlockhart

**Comment by dbatiste** [comment]
Hi @AleksandarMiha : the components are built with a certain look & feel to be consistent throughout our app, so there's limited API for configuration. If these existing options aren't flexible enough, my suggestion is to fork the repo and you are free to update the styles to suit your needs.  Do you mind me asking what app (and use-case) you are using the component with?
