### ISSUE TITLE
The Double Chin

### ISSUE THREAD

**Issue by maboelsoudd2l** [BrightspaceUI/dropdown#173]
When using when using dropdown, it is expected from a design perspective to have some extra space at the top and bottom, termed the "forehead" and "chin" respectively. However, when using `d2l-dropdown-menu`, there tends to be a residual double the space at the chin area, we are calling it the "Double Chin". The extra space in the bottom is too big for the design spec. Is there a way we can change this?
![image](https://user-images.githubusercontent.com/52468201/70934852-deed2000-200c-11ea-8f71-db643b94b127.png)

**Comment by dbatiste** [comment]
Yep, we _should_ be able to address the extra space at the bottom.
